name: brainoware_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py=3.7.0
  - ipykernel=6.15.2
  - matplotlib=3.5.3
  - numpy=1.21.5
  - pandas=1.3.5
  - pillow=9.2.0
  - pip=22.3.1
  - python=3.7
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - librosa=0.8.1
