name: brainoware_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - audioread=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2024.8.30
  - cffi=1.15.1
  - colorama=0.4.6
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.13.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.2
  - glib-tools=2.80.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5py=3.7.0
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.10
  - importlib-metadata=4.11.4
  - importlib-resources=6.0.0
  - importlib_resources=6.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - jedi=0.18.1
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.11.2
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.14
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.1
  - libclang13=14.0.6
  - libdeflate=1.14
  - libffi=3.5.2
  - libflac=1.5.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.2
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - liblapack=3.9.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libogg=1.3.5
  - libopus=1.6.1
  - libpng=1.6.39
  - libpq=16.11
  - librosa=0.8.1
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpg123=1.32.9
  - msgpack-python=1.0.4
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - numba=0.56.3
  - numexpr=2.8.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openjpeg=2.5.0
  - openssl=3.6.1
  - packaging=22.0
  - pandas=1.3.5
  - parso=0.8.3
  - pcre2=10.43
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - platformdirs=3.1.1
  - pooch=1.8.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2022.7
  - pywin32=305
  - pyzmq=22.3.0
  - qt-main=5.15.2
  - resampy=0.4.3
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.6.3
  - sip=6.5.1
  - six=1.16.0
  - soxr=0.1.3
  - soxr-python=0.3.2
  - sqlite=3.50.2
  - threadpoolctl=3.1.0
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.5
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.8.2
  - xz-tools=5.8.2
  - zeromq=4.3.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - charset-normalizer==3.4.3
      - requests==2.31.0
      - spykes==0.3.dev0
      - urllib3==2.0.7
prefix: D:\miniconda\envs\spykes
